### ISSUE TITLE
Bug in endpoint: endpoint.get(...).getJoin is not a function

### ISSUE THREAD

**Issue by ghost** [ironhee/graphql-server-example#1]
There is a bug in endpoint js. to use node(id:"ABC==")

You have to change 

`const resource await endpoint.get(id).getJoin().run();`
to
`const resource await endpoint.Model.get(id).getJoin().run();`

**Comment by ironhee** [comment]
Thank you :D 

Fixed!

**Comment by ironhee** [comment]
As soon as possible, I will make some refactoring with [nothinkdb](https://github.com/ediket/nothinkdb) and [nothinkdb-graphql](https://github.com/ediket/nothinkdb-graphql)

I appreciate your interest for this repo :D
